modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="jujutsucraftaddon"
version="10.0"
displayName="JJKUR"
displayURL="https://www.curseforge.com/members/satuxhi/projects"
logoFile="logo.png"
credits="Made By Satushi"
authors="Satushi"
description="Reworked Addon, Jujutsu Kaisen: Ultimate"

[[dependencies.jujutsucraftaddon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.jujutsucraftaddon]]
    modId="jujutsucraftaddon"
    mandatory=true
    versionRange="[10.0]"
    ordering="NONE"
    side="BOTH"


[[dependencies.jujutsucraftaddon]]
    modId="geckolib"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.jujutsucraftaddon]]
    modId="jujutsucraft"
    mandatory=true
    versionRange="[46.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.jujutsucraftaddon]]
    modId="playeranimator"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration